package js {
	/**
	 * ...
	 * @author army8735
	 * @version 5.0 build 20100305
	 */
	
	public class CallJs	{
		public static const INIT:String = 'function aaaa(p,w,x,y,q,i){function l(c){var d=c.textContent||c.innerText;if(!d&&c.firstChild)d=c.firstChild.nodeValue;return d||""}function r(){alert(i[2])}function k(c,d){if(d.length&&c.className.indexOf(d)==-1)if(c.className.length)c.className+=" "+d;else c.className=d}function s(c,d){if(d.length&&c.className.indexOf(d)!=-1)c.className=c.className==d?"":c.className.indexOf(d)==0?c.className.replace(d+" ",""):c.className.replace(" "+d,"")}var z=navigator.appName.indexOf("Microsoft")!=-1,m=0,j=[],t=null,h=null,n=null,v={exec:function(){if(t=z?window[q]:document[q]){for(var c=document.getElementsByTagName("pre"),d=document.getElementsByTagName("textarea"),e=0,b=c.length;e<b;e++)c[e].style.display!="none"&&c[e].className.indexOf(p)>-1&&j.push(c[e]);e=0;for(b=d.length;e<b;e++)d[e].style.display!="none"&&d[e].className.indexOf(p)>-1&&j.push(d[e]);this.parseNext()}},parseNext:function(){if(m<j.length){h=j[m++];t.parse(l(h),h.className)}},genRes:function(c,d,e,b,A){var g=document.createElement("div");k(g,x);k(g,b);b=document.createElement("p");b.innerHTML=c+" "+i[0];g.appendChild(b);b=document.createElement("div");b.className="copy";if(window.clipboardData&&window.clipboardData.setData){b.innerHTML=i[1];b.onclick=function(){window.clipboardData.setData("text",l(g.nextSibling))&&r()}}else b.innerHTML=\'<object data="\'+w+\'" type="application/x-shockwave-flash" width="100" height="20"><param name="wmode" values="transparent"/><param name="allowScriptAccess" value="always"/><param name="flashvars" value="copy=\'+m+"&lang="+i[1]+\'"/></object>\';g.appendChild(b);b=document.createElement("ol");b.start=d;b.className=c;b.innerHTML=A;b.style.paddingLeft=Math.max((String(b.childNodes.length).length+2)*9,30)+"px";b.onmouseover=function(a){a=a||window.event;for(a=a.srcElement||a.target;a.tagName&&a.tagName.toLowerCase()!="ol"&&a.tagName.toLowerCase()!="li";)a=a.parentNode;if(a.tagName.toLowerCase()=="li"){n&&s(n,"actived");k(a,"actived");n=a}};b.onclick=function(a){a=a||window.event;for(a=a.srcElement||a.target;a.tagName&&a.tagName.toLowerCase()!="ol"&&a.tagName.toLowerCase()!="li";)a=a.parentNode;if(a.tagName.toLowerCase()=="li"){a=a;var o=parseInt(a.rel||a.getAttribute("rel")),f=a.nextSibling;if(f){var u=f.className=="hide";if(!(a.className!="fold"&&(f.rel||f.getAttribute("rel"))<=o))for(u?s(a,"fold"):k(a,"fold");f&&parseInt(f.rel||f.getAttribute("rel"))>o;){if(parseInt(f.rel||f.getAttribute("rel"))<=o)break;f.className=u?"":"hide";f=f.nextSibling}}}};g.appendChild(b);h.parentNode.insertBefore(g,h);h.style.display="none";if(e>20&&b.clientHeight>e)b.style.height=e+"px";setTimeout(function(){v.parseNext()},0)},copy:function(c){setTimeout(r,100);return l(j[c-1])}};window[y]=v}';
	}
}