package js {
	/**
	 * ...
	 * @author army8735
	 */
	
	public class CallJs	{
		public static const INIT:String = 'function(n,r,s,t,o,h){function i(c){var b=c.textContent||c.innerText;!b&&c.firstChild&&(b=c.firstChild.nodeValue);return b||""}function p(){alert(h[2])}function j(c,b){b.length&&-1==c.className.indexOf(b)&&(c.className=c.className.length?c.className+(" "+b):b)}var k=-1!=navigator.appName.indexOf("Microsoft"),u=k&&!window.XMLHttpRequest,v=k&&window.addEventListener,l=0,f=[],q,e;window.__flash__escapeXML=function(c){var b={\'"\':"&quot;","<":"&lt;",">":"&gt;",\'"\':"&apos;"};return c.replace(/&/g,"&amp;").replace(/([\'"<>])/g,function(c,a){var e=b[a];return e?e:c})};var m={exec:function(){if(q=k&&!v?window[o]:document[o]){for(var c=document.getElementsByTagName("pre"),b=document.getElementsByTagName("textarea"),d=0,a=c.length;d<a;d++)"none"!=c[d].style.display&&-1<c[d].className.indexOf(n)&&f.push(c[d]);d=0;for(a=b.length;d<a;d++)"none"!=b[d].style.display&&-1<b[d].className.indexOf(n)&&f.push(b[d]);this.parseNext()}},parseNext:function(){l<f.length&&(e=f[l++],q.parse(i(e),e.className))},genRes:function(c,b,d,a,f){var g=document.createElement("div");j(g,s);j(g,a);a=document.createElement("p");a.innerHTML=c+" "+h[0];g.appendChild(a);a=document.createElement("div");a.className="copy";window.clipboardData&&window.clipboardData.setData?(a.innerHTML=h[1],a.onclick=function(){window.clipboardData.setData("text",i(g.nextSibling))&&p()}):a.innerHTML=\'<object data="\'+r+\'" type="application/x-shockwave-flash" width="100" height="20"><param name="wmode" value="transparent"/><param name="allowScriptAccess" value="always"/><param name="flashvars" value="copy=\'+l+"&lang="+h[1]+\'"/></object>\';g.appendChild(a);a=document.createElement("ol");a.start=b;a.className=c;a.innerHTML=f;a.style.paddingLeft=Math.max(9*((""+(a.childNodes.length+b)).length+2),30)+"px";a.onclick=function(a){a=a||window.event;for(a=a.srcElement||a.target;a.tagName&&a.tagName.toLowerCase()!="ol"&&a.tagName.toLowerCase()!="li";)a=a.parentNode;if(a.tagName.toLowerCase()=="li"){var c=parseInt(a.rel||a.getAttribute("rel")),b=a.nextSibling;if(b){var d=b.className=="hide";if(!(a.className!="fold"&&(b.rel||b.getAttribute("rel"))<=c)){if(d){if(a.className.indexOf("fold")!=-1)a.className=a.className=="fold"?"":a.className.indexOf("fold")==0?a.className.replace("fold ",""):a.className.replace(" fold","")}else j(a,"fold");for(;b&&parseInt(b.rel||b.getAttribute("rel"))>c;){if(parseInt(b.rel||b.getAttribute("rel"))<=c)break;b.className=d?"":"hide";b=b.nextSibling}}}}};g.appendChild(a);e.parentNode.insertBefore(g,e);e.style.display="none";d&&a.clientHeight>d&&(u?a.style.height=d+"px":a.style.maxHeight=d+"px");setTimeout(function(){m.parseNext()},0)},goOn:function(c){oCurrent.innerHTML+=c},copy:function(c){setTimeout(p,100);return i(f[c-1])}};window[t]=m;setTimeout(function(){m.exec()},0)}';
	}
}