package js {
	/**
	 * ...
	 * @author army8735
	 * @version 5.0 build 20100305
	 */
	
	public class CallJs	{
		public static const INIT:String = 'function(v,w,x,y,p){function l(c){var e=c.textContent||c.innerText;if(!e&&c.firstChild)e=c.firstChild.nodeValue;return e||""}function q(){alert("已复制到剪贴板中！")}function j(c,e){if(e.length&&c.className.indexOf(e)==-1)if(c.className.length)c.className+=" "+e;else c.className=e}function r(c,e){if(e.length&&c.className.indexOf(e)!=-1)c.className=c.className==e?"":c.className.indexOf(e)==0?c.className.replace(e+" ",""):c.className.replace(" "+e,"")}var z=navigator.appName.indexOf("Microsoft")!=-1,m=0,k=[],s=null,h=null,n=null,u={exec:function(){if(s=z?window[p]:document[p]){for(var c=document.getElementsByTagName("pre"),e=0,i=c.length;e<i;e++)c[e].style.display!="none"&&c[e].className.indexOf(v)>-1&&k.push(c[e]);this.parseNext()}},parseNext:function(){if(m<k.length){h=k[m++];s.parse(l(h),h.className)}},genRes:function(c,e,i,d,A){var g=document.createElement("div");j(g,x);j(g,d);d=document.createElement("p");d.innerHTML=c+" 代码";g.appendChild(d);d=document.createElement("div");d.className="copy";if(window.clipboardData&&window.clipboardData.setData){d.innerHTML="复制";d.onclick=function(){window.clipboardData.setData("text",l(g.nextSibling))&&q()}}else d.innerHTML=\'<object data="\'+w+\'" width="24" height="12" type="application/x-shockwave-flash"><param name="wmode" values="transparent"/><param name="flashvars" value="copy=\'+m+\'"/></object>\';g.appendChild(d);d=document.createElement("div");d.className="about";d.innerHTML="关于";d.onclick=function(){window.alert("Project: JSSC ver5.0\\nUrl: http://code.google.com/p/jssc/\\nLicense: GNU Lesser General Public License")};g.appendChild(d);d=document.createElement("ol");d.start=e;d.className=c;d.innerHTML=A;d.style.paddingLeft=Math.max((String(d.childNodes.length).length+2)*9,30)+"px";d.onmouseover=function(b){b=b||window.event;for(b=b.srcElement||b.target;b.tagName&&b.tagName.toLowerCase()!="ol"&&b.tagName.toLowerCase()!="li";)b=b.parentNode;if(b.tagName.toLowerCase()=="li"){n&&r(n,"actived");j(b,"actived");n=b}};d.onclick=function(b){b=b||window.event;for(b=b.srcElement||b.target;b.tagName&&b.tagName.toLowerCase()!="ol"&&b.tagName.toLowerCase()!="li";)b=b.parentNode;if(b.tagName.toLowerCase()=="li"){b=b;var o=parseInt(b.rel||b.getAttribute("rel")),f=b.nextSibling;if(f){var t=f.className=="hide";if(!(b.className!="fold"&&(f.rel||f.getAttribute("rel"))<=o))for(t?r(b,"fold"):j(b,"fold");f&&parseInt(f.rel||f.getAttribute("rel"))>o;){if(parseInt(f.rel||f.getAttribute("rel"))<=o)break;f.className=t?"":"hide";f=f.nextSibling}}}};g.appendChild(d);h.parentNode.insertBefore(g,h);h.style.display="none";if(i>20&&d.clientHeight>i)d.style.height=i+"px";setTimeout(function(){u.parseNext()},0)},copy:function(c){q();return l(k[c-1])}};window[y]=u}';
	}
}